version: '3.8'
services:
    backend:
        build:
            context: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home
        ports:
            - '8000:8000'
        stdin_open: true
        tty: true
        depends_on:
            - db

    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    app:
        build:
            context: ./app
        ports:
            - '3000:3000'
            - '3001:3001'
        depends_on:
            - backend
        volumes:
            - ./frontend:/app
            # One-way volume to use node_modules from inside image
            - /app/node_modules
